GOOGLE_CLIENT_ID:
GOOGLE_CLIENT_SECRET:
FACEBOOK_APP_ID:
FACEBOOK_APP_SERECT:
TWITTER_APP_ID:
TWITTER_APP_SERECT:
LINKEIN_APP_ID:
LINKEIN_APP_SECRET:
STRIPE_PUBLISHABLE_KEY:
STRIPE_SECRET_KEY:
MAIL_ADDRESS:
MAIL_PORT:
MAIL_DOMAIN:
MAIL_USERNAME:
MAIL_PASSWORD:
INSTAGRAM_CLIENT_ID:
INSTAGRAM_CLIENT_SECRET:
